# -*- coding: utf-8 -*-
"""IOURING-Task_NEW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9Sxt7XGhdpJs6uucGGyaVJoKJ4afxU8
"""

import pandas as pd


def calculate_sma(data, column_name, window):
    return data[column_name].rolling(window=window, min_periods=1).mean()
data = pd.read_csv('/content/RELIANCE_new.csv')
columns_to_calculate = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']
window_size = 10
for column in columns_to_calculate:
    sma_column_name = f"SMA({column}) {window_size}D"
    data[sma_column_name] = calculate_sma(data, column, window_size)
output_file = '/content/RELIANCE_updated.csv'
data.to_csv(output_file, index=False)

print(f"SMA calculation completed. Updated file saved as {output_file}")